---
- name: Deploy the Raspberry Pi 4 🍓
  hosts: all
  become: yes
  become_user: root
  remote_user: "{{ ansible_ssh_user }}"
  gather_facts: yes

  collections:
    - containers.podman

  vars_files:
    - defaults/main.yml

  pre_tasks:
    - name: Check if the OS is Debian-based
      assert:
        that: "'Debian' in ansible_facts.os_family"
        fail_msg: "The Operating System is **not** Debian based ({{ ansible_facts.os_family }})!"
        success_msg: "The Operating System is Debian based, All good !"

  roles:
    - { role: "base", tags: "base" }
    - { role: "printer", tags: "printer" }
    - { role: "docker", tags: "docker" }
    - { role: "samba", tags: "samba" }

  post_tasks:
    - name: "Start and enable multiple services : {{ services | join(', ') }}"
      service:
        name: fail2ban
        state: restarted
        enabled: yes
      with_items: "{{ services }}"
      no_log: true

    - name: Systemd daemon reload
      systemd:
        daemon_reload: yes
        daemon_reexec: yes
      no_log: true
