---
- name: Create directories for scanner
  file:
    path: "/mnt/externalHDD/{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - scans
    - scans/images
    - scans/config

- name: ScannerJS - Pull Docker image
  containers.podman.podman_image:
    name: sbs20/scanservjs
    pull: yes
    tag: latest

- name: ScannerJS - Run container using podman
  containers.podman.podman_container:
    name: scanservjs
    image: sbs20/scanservjs:latest
    command: "--device=/dev/bus/usb/001/003:/dev/bus/usb/001/003"
    state: started
    restart_policy: on-failure:5
    recreate: yes
    restart: yes
    device: /dev/bus/usb/001/003:/dev/bus/usb/001/003:rw
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /mnt/externalHDD/scans/images:/app/data/output
      - /mnt/externalHDD/scans/config:/app/config
    ports: "1025:8080"
    expose: 8080
    user: "0:1003"
    memory: "512m"
    generate_systemd:
      path: /etc/systemd/system
  retries: 3
  delay: 3
  register: scContainer
  until: scContainer is not failed
