---
- name: Update the system
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install new packages
  apt:
    name: "{{ packages }}"
    state: latest

- name: Make a cron to update the system
  cron:
    name: update_apt
    user: root
    special_time: weekly
    backup: yes
    job: "apt-get update -y; apt-get upgrade -y; apt-get autoremove -y"

- name: Install NPM packages
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
  loop:
    - n
    - yarn

- name: Install NodeJS LTS version
  command: "n lts"

- name: Cockpit - Créé le fichier de configuration
  copy:
    src: cockpit.conf
    dest: /etc/cockpit/

- name: Mount a disk (/dev/sda1) to /mnt/externalHDD
  mount:
    path: /mnt/externalHDD
    src: /dev/sda1
    fstype: ext4
    state: mounted
